package sim.storage.cli;

public class WorkloadReadException extends RuntimeException {

	/** This value is generated by Eclipse IDE. */
	private static final long serialVersionUID = 3267945299901434376L;

	public WorkloadReadException() {
		super();
	}

	public WorkloadReadException(String message) {
		super(message);
	}
}
