package sim.storage.state;

public class IllegalDiskStateException extends RuntimeException {


	// this UID is generated by IDE.
	private static final long serialVersionUID = 1L;

	public IllegalDiskStateException() {
		super();
	}

	public IllegalDiskStateException(String message) {
		super(message);
	}

}
